export const profiledetails = [
    {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@example.com",
      phone: "+1-555-1234",
      age: 30,
      gender: "Male",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zipCode: "10001",
      },
      company: "TechCorp",
      jobTitle: "Software Engineer",
      salary: 75000,
      isActive: true,
      createdAt: "2024-02-03T10:00:00Z",
      updatedAt: "2024-02-03T12:00:00Z",
      hobbies: ["Reading", "Cycling", "Gaming"],
      skills: ["JavaScript", "React", "TypeScript"],
      preferences: {
        newsletter: true,
        notifications: false,
      },
      socialMedia: {
        linkedin: "https://linkedin.com/in/johndoe",
        github: "https://github.com/johndoe",
      },
      notes: "This is a sample user data.",
    },
    {
      id: 2,
      firstName: "Jane",
      lastName: "Doe",
      email: "janedoe@example.com",
      phone: "+1-555-5678",
      age: 28,
      gender: "Female",
      address: {
        street: "456 Elm St",
        city: "San Francisco",
        state: "CA",
        zipCode: "94101",
      },
      company: "TechCorp",
      jobTitle: "Product Manager",
      salary: 85000,
      isActive: true,
      createdAt: "2024-02-01T08:30:00Z",
      updatedAt: "2024-02-03T10:15:00Z",
      hobbies: ["Running", "Photography", "Reading"],
      skills: ["Product Management", "Agile", "UX Design"],
      preferences: {
        newsletter: true,
        notifications: true,
      },
      socialMedia: {
        linkedin: "https://linkedin.com/in/janedoe",
        github: "https://github.com/janedoe",
      },
      notes: "Passionate about user experience.",
    },
    {
      id: 3,
      firstName: "Alice",
      lastName: "Smith",
      email: "alicesmith@example.com",
      phone: "+1-555-7890",
      age: 35,
      gender: "Female",
      address: {
        street: "789 Maple Ave",
        city: "Chicago",
        state: "IL",
        zipCode: "60601",
      },
      company: "DataCorp",
      jobTitle: "Data Scientist",
      salary: 90000,
      isActive: false,
      createdAt: "2023-12-15T09:45:00Z",
      updatedAt: "2024-01-20T14:25:00Z",
      hobbies: ["Machine Learning", "Cooking", "Gaming"],
      skills: ["Python", "Machine Learning", "SQL"],
      preferences: {
        newsletter: false,
        notifications: false,
      },
      socialMedia: {
        linkedin: "https://linkedin.com/in/alicesmith",
        github: "https://github.com/alicesmith",
      },
      notes: "Loves data and AI.",
    },
    {
      id: 4,
      firstName: "John",
      lastName: "Doe",
      email: "johndoe2@example.com",
      phone: "+1-555-1111",
      age: 32,
      gender: "Male",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zipCode: "10001",
      },
      company: "TechCorp",
      jobTitle: "Software Engineer",
      salary: 75000,
      isActive: true,
      createdAt: "2024-01-10T11:00:00Z",
      updatedAt: "2024-02-03T12:00:00Z",
      hobbies: ["Reading", "Cycling", "Gaming"],
      skills: ["JavaScript", "React", "TypeScript"],
      preferences: {
        newsletter: true,
        notifications: false,
      },
      socialMedia: {
        linkedin: "https://linkedin.com/in/johndoe2",
        github: "https://github.com/johndoe2",
      },
      notes: "Duplicate name with different email.",
    },
    {
      id: 5,
      firstName: "Michael",
      lastName: "Brown",
      email: "michaelbrown@example.com",
      phone: "+1-555-2222",
      age: 40,
      gender: "Male",
      address: {
        street: "321 Oak St",
        city: "Seattle",
        state: "WA",
        zipCode: "98101",
      },
      company: "FinCorp",
      jobTitle: "Finance Manager",
      salary: 95000,
      isActive: true,
      createdAt: "2023-11-01T14:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
      hobbies: ["Investing", "Golf", "Chess"],
      skills: ["Finance", "Excel", "Risk Analysis"],
      preferences: {
        newsletter: false,
        notifications: true,
      },
      socialMedia: {
        linkedin: "https://linkedin.com/in/michaelbrown",
        github: "https://github.com/michaelbrown",
      },
      notes: "Enjoys market analysis.",
    },
  ];